version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    day: saturday
    time: "04:00"
    timezone: America/New_York
  open-pull-requests-limit: 10
  assignees:
  - znicholasbrown
  ignore:
  - dependency-name: eslint
    versions:
    - 7.24.0
  - dependency-name: sinon
    versions:
    - 10.0.0
  - dependency-name: vuetify
    versions:
    - 2.4.2
    - 2.4.3
    - 2.4.4
    - 2.4.5
    - 2.4.6
    - 2.4.7
    - 2.4.9
  - dependency-name: cronstrue
    versions:
    - 1.108.0
    - 1.109.0
    - 1.111.0
  - dependency-name: y18n
    versions:
    - 4.0.1
  - dependency-name: "@vue/cli-plugin-babel"
    versions:
    - 4.5.11
    - 4.5.12
  - dependency-name: "@auth0/auth0-spa-js"
    versions:
    - 1.13.6
    - 1.14.0
  - dependency-name: "@vue/cli-service"
    versions:
    - 4.5.11
    - 4.5.12
  - dependency-name: d3-dag
    versions:
    - 0.6.2
    - 0.6.3
  - dependency-name: elliptic
    versions:
    - 6.5.4
  - dependency-name: "@babel/plugin-proposal-optional-chaining"
    versions:
    - 7.12.16
    - 7.12.7
    - 7.13.8
  - dependency-name: moment-timezone
    versions:
    - 0.5.32
    - 0.5.33
  - dependency-name: ini
    versions:
    - 1.3.8
  - dependency-name: jwt-decode
    versions:
    - 3.1.2
  - dependency-name: object-path
    versions:
    - 0.11.5
  rebase-strategy: disabled
